import sys

print(" ")
print("THe scrpit you're runnin' is '%s'" %str(sys.argv[0]))
print("There are %s arguments in the list  "%str(len(sys.argv)))
print(" ")
print("List of arguments: ", str(sys.argv))
print("Third argument is:", str(sys.argv[3]))
print(sys.argv)
print(" ")
print(sys.platform)
print("")
print("sys path is:")
print(sys.path)
print("")
print("Version of the interpreter:", sys.version)